# Site settings
author: Tiffany Leigh
title: Tiffany Leigh
header-img: img/home-bg.png
email: tiffanyleigh.10@gmail.com
copyright_name: Tiffany Leigh
description: > # this means to ignore newlines until "baseurl:"
  web developer blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pz0995

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
