# Site settings
title: 
header-img: img/home-bg.png
email: tiffanyleigh.10@gmail.com
copyright_name: pz0995
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pz0995
learn_profile: pz0995
email_username: tiffanyleigh.10@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
